# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# ignore all warnings from all pods
inhibit_all_warnings!
# in the Podfile means that we want the listed frameworks to be dynamically installed instead as static frameworks.
use_frameworks!

target 'keyChainTest' do
  # Pods for keyChainTest

end

target 'keyChainTest2' do
  # Pods for keyChainTest2
  pod 'Firebase/Core'
  pod 'Crashlytics'
end
