# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'keyChainTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for keyChainTest

end

target 'keyChainTest2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Fabric'
  pod 'Crashlytics'

  # Pods for keyChainTest2

end
